### ISSUE TITLE
Request password reset for my account

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/wpsite#11]
Unable to log onto wordpress as an editor. @aeiras @rstjames please have my password regenerated.

**Comment by aeiras** [comment]
sent, let me know if you have access now. :)

**Comment by Emily-Jiang** [comment]
nope. I didn't get the email.

**Comment by aeiras** [comment]
I resent and also sent you a private email with the password. 
May I use your personal email to provide you with new account edit access?

**Comment by Emily-Jiang** [comment]
emijiang6@googlemail.com  Thanks @aeiras  ! Very much appreciated!

**Comment by aeiras** [comment]
sent! 
Next week, I will check wordpress to make sure to delete your work email, etc. We can re-start it. it seems an issue with not-use.
