### ISSUE TITLE
Add information about the latest release at the top of the landing page

### ISSUE THREAD

**Issue by OndroMih** [microprofile/wpsite#3]
Information about the latest MicroProfile release is not visible when the landing page is loaded. I need to scroll 2 screens down to find it.

Solution:

Add basic information about the latest release with a download button at the top of the landing page. Maybe under the text "Eclipse MicroProfile Optimizing Enterprise Java for a Microservices Architecture".

**Comment by rstjames** [comment]
@OndroMih 
Agree, I can put some information about the latest release on the top card. 
Do others feel this is information that should be shown first? 

Thanks!

**Comment by cealsair** [comment]
Ondro makes a good point. The "See The Code" button is at the top right but you have to scroll down to download the PDF spec doc. Getting the PDF to the latest doc is a high-interest asset whenever there's a new release.

**Comment by rstjames** [comment]
Ok I added this section to the top card. 
Here is how it looks:
<img width="1275" alt="screenshot 2019-01-21 10 26 39" src="https://user-images.githubusercontent.com/12132146/51464961-143eae80-1d67-11e9-9551-a86c1098da07.png">

**Comment by cealsair** [comment]
Completed and live. Thank you Ryan.

**Comment by OndroMih** [comment]
Good job @rstjames @cealsair, it looks good.
