### ISSUE TITLE
The "Want to be a Contributor?" button goes to a yaml file

### ISSUE THREAD

**Issue by alewis001** [microprofile/wpsite#5]
Clicking the "Want to be a Contributor?" button at the top of the https://microprofile.io/contributors/ page takes you to: https://github.com/microprofile/microprofile-site-config/blob/master/site.yaml

I assume that button should be taking the user to something like: https://projects.eclipse.org/projects/technology.microprofile/developer

As contributions can come in many forms, maybe a page titled Developer may give the wrong impression about it only being for people writing code. However, the opening "Welcome!" of that page is the right content and includes contributions outside of code.

**Comment by aeiras** [comment]
good feedback @alewis001!

Adding @rstjames to look at this ticket :) Thanks!
